export const SET_CURRENT_LOCATION = "SET_CURRENT_LOCATION"; 

export const MODAL_VISIBLE = "MODAL_VISIBLE"; 
export const BACKDROP_CLICKED = "BACKDROP_CLICKED";

export const FETCH_PLAN_START = "FETCH_PLAN_START";
export const FETCH_PLAN_SUCCESS = "FETCH_PLAN_SUCCESS";
export const FETCH_PLAN_FAIL = "FETCH_PLAN_FAIL";

export const ADD_MY_PLAN = "ADD_MY_PLAN";
export const ADD_PLAN_START = "ADD_PLAN_START";
export const ADD_PLAN_SUCCESS = "ADD_PLAN_SUCCESS";
export const ADD_PLAN_FAIL = "ADD_PLAN_FAIL";

export const LOCK_PLAN_ITEM = "LOCK_PLAN_ITEM";
export const FINISH_PLAN_ITEM = "FINISH_PLAN_ITEM";
export const DELETE_PLAN_ITEM = "DELETE_PLAN_ITEM";

export const FETCH_FOLLOWER = "FETCH_FOLLOWER";
